### ISSUE TITLE
Resources [MLX 2023]

### ISSUE THREAD

**Issue by pulgamecanica** [denisebitca/42utils#2]
# Why I bring this issue?
***
> I wanted to suggest a few resources that helped me complete some of the graphical projects with minilibx projects.
> Regarding Cub3D and Fract-ol

## Resources for understanding MLX

+ Understand how mlx works by [harm-smits](https://harm-smits.github.io/42docs/libs/minilibx/getting_started.html)
***
+ How to install mlx [Installation guide](https://pulgamecanica.herokuapp.com/posts/mlx-starter-pack)?
***
+ How Raycasting works [tutorial by permadi](https://permadi.com/1996/05/ray-casting-tutorial-table-of-contents/)
***

Amazing work, keep it up.
Let me know if the info is relevant, perhaps I missunderstood what this project was for!

**Comment by denisebitca** [comment]
Will add this later today, thanks for the contribution!
